	- platform: template
		name: "power"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xE51A
	- platform: template
		name: "input"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xEE11
	- platform: template
		name: "profile"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xDB24
	- platform: template
		name: "menu"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xA35C
	- platform: template
		name: "back"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xBD42
	- platform: template
		name: "up"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xE718
	- platform: template
		name: "down"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xEF10
	- platform: template
		name: "left"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xA857
	- platform: template
		name: "right"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xB04F
	- platform: template
		name: "enter"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xAC53
	- platform: template
		name: "aux1"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xAC53
	- platform: template
		name: "aux2"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xC639
	- platform: template
		name: "aux3"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xC53A
	- platform: template
		name: "1"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xF40B
	- platform: template
		name: "2"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xF807
	- platform: template
		name: "3"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xFC03
	- platform: template
		name: "4"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xF50A
	- platform: template
		name: "5"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xF906
	- platform: template
		name: "6"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xFD02
	- platform: template
		name: "7"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xF609
	- platform: template
		name: "8"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xFA05
	- platform: template
		name: "9"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xFE01
	- platform: template
		name: "10"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xDA25
	- platform: template
		name: "11"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xD926
	- platform: template
		name: "12"
		on_press:
			- remote_transmitter.transmit_nec:
				address: 0xB649
				command: 0xD827
